### ISSUE TITLE
Allow example() api to accept override object for explicit value setting.

### ISSUE THREAD

**Issue by Samueljoli** [xogroup/felicity#119]
#### Context

New Feature Request

#### What are you trying to achieve?

Allow `Felicity.example()` to accept override object to explicitly set the value of some or all properties.

```js
const schema = Joi.object().keys({
  director   : Joi.string(),
  distributor: Joi.number()
});

class Film extends Felicity.entityFor(schema) {};

const instance = new Film();
const overrideOptions = {
  director   : 'Steve McQueen',
}
const example = instance.example(overrideOptions);
```

**Comment by WesTyler** [comment]
Will discuss more later, but for now check out the discussion previously [here](https://github.com/xogroup/felicity/issues/95).

Definitely worth revisiting.

**Comment by Samueljoli** [comment]
I'll go ahead start off by echoing this `Rules for partial inclusion of data started getting hairy pretty quickly as I was putting together a spike for this.` I also see Lam's point. 

I'd imagine a revisit is dependent on community need?

**Comment by WesTyler** [comment]
Yeah, after letting this sit for a bit and looking at a few options  I think it is best left to the user so that Felicity doesn't have to try to encapsulate all rules for conflicts/partial inclusion. I'll drop a sample here shortly for posterity.

**Comment by WesTyler** [comment]
```js
const Felicity = require('felicity');
const Hoek = require('hoek');
const Joi = require('joi');

const schema = Joi.object().keys({
    id: Joi.string().guid().required(),
    things: Joi.array().optional(),
    name: Joi.string().allow(null)
});
const Document = Felicity.entityFor(schema);

const generateExample = (overrideValues) => {
    const example = Document.example({
        config: {
            includeOptional: true, // Populate all properties on the schema
            ignoreValids   : true // Do not use "null" example for properties with .allow(null) on the schema
        }
    });

    return Hoek.applyToDefaults(example, overrideValues, true);
};


Document.example(); // { id: '8ea8608c-f10b-4015-9665-7f3e83718952', name: null }
generateExample({ name: 'document name' }); // { id: '9b8fc6d8-3ccf-4f3e-96b5-d5ffbd91d735', things: [], name: 'document name' }
```
