### ISSUE TITLE
Support options override on entityFor .validate() calls

### ISSUE THREAD

**Issue by WesTyler** [xogroup/felicity#123]
Currently calls to `.validate()` do not support passing in additional or override options (like `{ stripUnknown: true }`). The only options are those set at the time that `entityFor` is called.

We should allow for optional overrides at the time of validation.

**Comment by Samueljoli** [comment]
@WesTyler Are you currently working on this?

**Comment by WesTyler** [comment]
@Samueljoli nope. Was going to today and ended up on scss styling all day. I'll un-assign myself if you want to take a stab at it!

**Comment by WesTyler** [comment]
This was back-ported to v2 in version 2.4.0
