### ISSUE TITLE
Raise an error when constructor is passed invalid input

### ISSUE THREAD

**Issue by Samueljoli** [xogroup/felicity#130]
#### Context

* *node version*: `8`
* *felicity version*: `2.x.x`
* *environment* (node, browser): `node`

#### What are you trying to achieve or the steps to reproduce ?

Using a felicity constructor and input options, successfully create an instance, and through an error when passed an invalid input.

```js
const subSchema = Joi.object().keys({
  name : Joi.string(),
  title: Joi.string()
}).options({
  presence: 'required'
});

const schema = Joi.object().keys({
  title    : Joi.string(),
  director : Joi.number(),
  producers: Joi.array().items(subSchema).allow(null, '').optional().default(null)
});

const input = {
  name     : 'Blade Runner',
  director : 'Denis Villeneuve',
  writers: [
    {
      name: 'Hampton Fancher'
    }
  ]
};

const Constructor = new Felicity.entityFor(schema);

const instance = new Constructor(input);

//... It would be nice if there some validation error thrown when the input doesn't fit the schema, in this case, title is required in subschema, yet one was not provided in input. 

```

**Comment by WesTyler** [comment]
I'm honestly torn about this. It was specifically designed not to throw in this case.

I'll ping a larger group to see if we can come to a consensus.

**Comment by WesTyler** [comment]
Pulling over some decisions from discussions in private channels:

It looks like we can add this as an option while preserving backward-compatibility by changing the signature of the constructor return by `entityFor` from `(input)` to `(input, [options])` where the optional `options` object would default to `{ validateInput: false }`. Calling the constructor with `new Constructor(input, { validateInput: true })` would enable the error throwing at the instance-level.

Additionally, there can be a new flag added to the existing `entityFor` options to set `validateInput: true` for all instances of the resulting Constructor if you do not want instance-level granularity.

```js
const Thing = new Felicity.entityFor(schema); // validateInput defaults to false
const thing = new Thing(wrongInput); // no error, bad input is simply ignored.
const thing = new Thing(wrongInput, { validateInput: true }); // throw ValidationError

const Constructor = new Felicity.entityFor(schema, { validateInput: true });
const instance = new Constructor(badInput);  // throw ValidationError
```

**Comment by WesTyler** [comment]
After sleeping on this, the second option is wrong. I'm not going to go down that road. 

The first option, while slightly inconvenient, is a well-established pattern in JS. I'm running with that. Feel free to hit me up if you disagree.

**Comment by WesTyler** [comment]
This was back-ported to v2 in version 2.4.0
