### ISSUE TITLE
Allow for optional override options to be provided to entityFor constructors.

### ISSUE THREAD

**Issue by WesTyler** [xogroup/felicity#131]
Related to the proposed solution to #130 .

We want to allow for instance-level options overrides for things such as `includeOptional` and the new (to-be-added)`validateInput` option. However, if we change the constructor function signature from `(input) => {}` to `(input, options) => {}` we do not have a convenient way to provide options but not input.

```js
const Thing = Felicity.entityFor(schema); // default option includeOptional: false
const thing = new Thing(input, { includeOptional: true }); // no problem, input and options both provided.
const problem = new Thing({ includeOptional: true }); // options is now taken as input. PROBLEM.
```

"Solution" 1 - require 2 params, a la `bind` and `call` (for which the first param is always context).
```js
const noProblem = new Thing(null, { includeOptional: true }); // input is null, options are accepted
```

"Solution" 2 - overloaded input parameter to allow for psuedo-named-params:
```js
const normalInput = new Thing({ prop1: 'a', prop2: {} }); // input accepted as normal to maintain backward-compat.
const overloadedInput = new Thing({ input: { /**/ }, options: { /**/} }); // input pulled from "input.input", options pulled from "input.options". Allows for either/or to be included as desired.
```

I don't love the overloaded param option, since it breaks the JS standard of constructor functions. I also don't love overloaded params to begin with. If nobody provides any input I will run with Solution 1.

**Comment by Samueljoli** [comment]
@WesTyler How exactly would `1` work in terms of passing the `input`?

**Comment by WesTyler** [comment]
If there was actual input, it would be the same as it is right now:

```js
const Thing = Felicity.entityFor(schema);
const thing = new Thing(inputObject);
const thingWithOptions = new Thing(inputObject, optionsObject);
```

It just gets "weird" if you want to instantiate an "empty" instance with options.
```js
const emptyThing = new Thing(); // same behavior as current version
const emptyThingWithOptions = new Thing(null, optionsObject);
```

**Comment by WesTyler** [comment]
After sleeping on this, the second option is wrong. I'm not going to go down that road.

The first option, while slightly inconvenient, is a well-established pattern in JS. I'm running with that. Feel free to hit me up if you disagree.

**Comment by WesTyler** [comment]
This was back-ported to v2 in version 2.4.0
