### ISSUE TITLE
Example with bool type throws

### ISSUE THREAD

**Issue by rbeer** [xogroup/felicity#138]
#### Context

* *node version*: 8.9.4
* *felicity version*: 2.4.5
* *joi version*: 6.10.1
* *environment* (node, browser): node
* *any relevant modules used with* (hapi, hoek, etc.): ---
* *any other relevant information*: ---

#### What are you trying to achieve or the steps to reproduce ?
Create `example()` for a Joi schema with `bool` type.

```js
> const Joi = require('joi')                                    [9/954]
undefined
> const messageSnippetSchema = Joi.object({
...   type: Joi.string().allow('textMessageEvent').required(),
...   liveChatId: Joi.string().required(),
...   displayMessage: Joi.string().required(),
...   authorChannelId: Joi.string().required(),
...   publishedAt: Joi.string().required(),
...   hasDisplayContent: Joi.boolean().required()
... });
undefined
> messageSnippetSchema
{ isJoi: true,
  _type: 'object',
  _settings: null,
  _valids: { _set: [] },
  _invalids: { _set: [] },
  ...
  _inner:
   { children: [ [Object], [Object], [Object], [Object], [Object], [Obj
ect] ],
     ... }
> const fel = require('felicity')
undefined
> const fctor = fel.entityFor(messageSnippetSchema);
undefined
> const f = new fctor();
undefined
> f.example()
TypeError: Cannot read property 'slice' of undefined
    at BooleanExample._generate (/home/carebear/code/russian-mainframe/
node_modules/felicity/lib/valueGenerator.js:397:57)
    at BooleanExample.generate (/home/carebear/code/russian-mainframe/n
ode_modules/felicity/lib/valueGenerator.js:63:21)
    at Object.keys.forEach (/home/carebear/code/russian-mainframe/node_
modules/felicity/lib/valueGenerator.js:653:48)
    at Array.forEach (<anonymous>)
    at ObjectExample._generate (/home/carebear/code/russian-mainframe/n
ode_modules/felicity/lib/valueGenerator.js:628:53)
...
```

#### What result did you expect ?
Example Object for schema.
#### What result did you observe ?
The valueGenerator(.js) expects `truthy()` and `falsy()` (reflected as Arrays) on `bool` types to determine the example's value. Joi's `.bool()/.boolean()` type doesn't have `falsy()/truthy()` 'setters' (anymore?).

Line 396; neither `.truthy`, nor `.falsy` exist on `schemaDescription`
https://github.com/xogroup/felicity/blob/f21d1da7429cba7e3bb436832841efb1468102f7/lib/valueGenerator.js#L391-L402

**Comment by rbeer** [comment]
Yeah, I guess that one's gone, isn't it?
```
{ key: 'hasDisplayContent',
          schema:
           { isJoi: true,
             _type: 'boolean',
             _settings: null,
             _valids: { _set: [] },
             _invalids: { _set: [] },
             _tests: [],
             _refs: [],
             _flags: { presence: 'required' },
             _description: null,
             _unit: null,
             _notes: [],
             _tags: [],
             _examples: [],
             _meta: [],
             _inner: {} } }
```

**Comment by rbeer** [comment]
joi: ^6.10
Nevermind 😅

**Comment by WesTyler** [comment]
Haha glad you got it figured out! I was having a mild freakout reading the original issue template :)

Thanks for checking out Felicity and taking the time to open an issue! I appreciate the effort even if it turned out to be a non-issue :D

**Comment by rbeer** [comment]
Well, whenever I miss something in Felicity, I'll be back. :)
I actually came across the version discrepancy when I pulled the repo to start working on a PR.
You guys saved me a ton of time with this, already. It will be my pleasure to contribute, once my needs outgrow what Felicity already does. So, then again, don't expect me back too soon. ;D
