### ISSUE TITLE
.example() on string().required().valid(a, b, c).default(b) does not take default into account

### ISSUE THREAD

**Issue by gxapplications** [xogroup/felicity#139]
#### Context

* *node version*: 7.x
* *felicity version*: 2.4.5
* *environment* (node, browser): node API server side

#### What are you trying to achieve or the steps to reproduce ?

Get an .example() value from a schema with a key of type enum:
var dataSchema = Joi.string().required().valid('invert', 'off', 'on').default('invert')

Using only default() values:
felicity.example(dataSchema, { config: { ignoreValids : true, ignoreDefaults: false }})

In my case I don't want a random value into .valid() choices, I need the default value, so I set:
ignoreValids to true
ignoreDefaults to false

#### What result did you expect ?

'invert'

#### What result did you observe ?

'mf0gt4aec7n96oe4nvxekx1or' : a random value that does not use .default() from schema.

**Comment by WesTyler** [comment]
Thank you for finding and letting us know about this! I'll take a look today and see if I can get a fix out soon.

**Comment by WesTyler** [comment]
Got this patched in master. Backporting to v2.x.x now.

**Comment by WesTyler** [comment]
Okay, this was published in 2.4.6

Please let me know if you continue to see issues with this!


Thank you for checking out Felicity and taking the time to help us make it better! I really appreciate it! :D
