### ISSUE TITLE
Update to Joi 14

### ISSUE THREAD

**Issue by WesTyler** [xogroup/felicity#148]
Felicity needs to be updated to and tested against Joi 14.

**Comment by WesTyler** [comment]
In progress. Includes breaking changes in Joi around `.example()`, so this will be a semver major release for v4. 

Going to try to get some bug fixes into 3.x before rebasing and PRing this, but the local commit is done.

**Comment by mattkelly** [comment]
@WesTyler do you happen to have an ETA for this? I'm interested in support for Joi 14.

**Comment by WesTyler** [comment]
Hey @mattkelly sorry, didn't realize anyone was watching and waiting on this :P 

I'll double check 3.x tomorrow to make sure I've got that in good shape. If so I can get 4.0.0 to support Joi@14 published tomorrow afternoon.

**Comment by WesTyler** [comment]
Felicity@4.0.0 is published with support for Joi@14 :)

**Comment by mattkelly** [comment]
Thanks a ton for the fast turnaround on this, @WesTyler! I'll check it out. I really appreciate it.

**Comment by WesTyler** [comment]
Haha I don't know that I can claim fast turnaround when I opened the issue to do this about a month ago. Thank *you* for reminding me it was sitting here!
