### ISSUE TITLE
Felicity Logo

### ISSUE THREAD

**Issue by WesTyler** [xogroup/felicity#18]
Once again following Hapi.js patterns:

create `/images` directory in repo root; drop `png`(s).
README: `![felicity Logo](https://raw.github.com/xogroup/felicity/master/images/felicity.png)`

**Comment by devinivy** [comment]
You might want an .npmignore too, to make sure the images are not published https://github.com/hapijs/joi/blob/master/.npmignore

**Comment by WesTyler** [comment]
Cool, good call out. Thanks!

**Comment by WesTyler** [comment]
Meh, this is apparently never going to happen
