### ISSUE TITLE
Track Joi support coverage

### ISSUE THREAD

**Issue by WesTyler** [xogroup/felicity#21]
Just creating a place to track with Joi schema features we currently support.
A feature/option is "supported" when there are explicit tests in both Felicity.skeleton and Felicity.example.

Joi version: 9.0.4
- Any
  - `default` ✅ 
  - `required`✅
  - `optional`✅
  - `valid` ✅
  - `allow` ✅
  - `strip` ✅
  - `forbidden` ✅
- String
  - `guid`✅
  - `email`✅
  - `min`✅
  - `max`✅
  - `length`✅
  - `isoDate`✅
  - `regex` ✅
    - `invert: true` :x:
  - `insensitive` ✅
  - `truncate` ✅
  - `creditCard` ✅
  - `replace` ✅
  - `alphanum` ✅
  - `token` ✅
  - `ip` ✅
  - `uri` :x:
  - `uuid` ✅
  - `hex` ✅
  - `hostname` ✅
  - `lowercase` ✅
  - `uppercase` ✅
  - `trim` ✅
- Number
  - `negative`✅
  - `positive`✅
  - `integer`✅
  - `min`✅
  - `max`✅
  - `greater`✅
  - `less`✅
  - `precision`✅
  - `multiple`✅
- Boolean
  - `truthy` ✅
  - `falsy` ✅
- Buffer
  - `encoding`✅
  - `min`✅
  - `max`✅
  - `length`✅
- Date
  - `min`✅
    - `now`✅
  - `max`✅
    - `now`✅
  - `iso`✅
  - `timestamp`✅
    - `unix`✅
  - `format`✅
- Function
  - `arity(1)`✅
  - `arity` ✅
  - `minArity` ✅
  - `maxArity` ✅
  - `ref` :x:
- Array
  - `items`✅
    - `forbidden`✅
  - `sparse`✅
  - `ordered`✅
  - `min`✅
  - `max`✅
  - `length`✅
  - `single` ✅
  - `unique` :x:
- Alternatives
  - `try`✅
  - `when`✅
- Object
  - `keys`✅
  - `min`✅
  - `max`✅
  - `length`✅
  - `nand`✅
  - `xor`✅
  - `with`✅
  - `without`✅
  - `pattern` :x:
  - `and` ✅
  - `or` ✅
  - `rename` ✅
  - `unknown` ✅
  - `type` ✅
  - `schema` ✅
  - `requiredKeys` :x:
  - `optionalKeys` :x:

**Comment by WesTyler** [comment]
(Edited to add any `forbidden`, `strip`, and `allow`)

**Comment by lamchakchan** [comment]
(Edited to add function `arity(n)`, `minArity(n)` and `maxArity(n)`)

**Comment by lamchakchan** [comment]
(Edited to add array `single`)

**Comment by lamchakchan** [comment]
(Edited to add string `ip`)

**Comment by lamchakchan** [comment]
(Edited to add string `uppercase` and `lowercase`)

**Comment by lamchakchan** [comment]
@WesTyler I don't think all of these API contracts from `joi` needs to be supported.  It looks like some of these contracts are actually actions and not validations that we can reverse generate a value from.  Check [this](https://github.com/hapijs/joi/blob/master/API.md#stringreplacepattern-replacement) out.

**Comment by lamchakchan** [comment]
@WesTyler Looks like you already took care of `date.format([string])`.  I'm looking at [here](https://github.com/xogroup/felicity/blob/master/test/value_generator_tests.js#L767-L778).

**Comment by WesTyler** [comment]
@lamchakchan re: `date.format` you're right. I updated the README but not this issue when I made the PR. Issue is now updated. Thanks!

For the action contracts, you're right. I want to have at minimum a test on Felicity.entityFor though, just to make sure there are no unknown Joi internals that interfere with how Felicity is interacting with the `describe` api for those options.

**Comment by WesTyler** [comment]
(Edited to indicate `string.truncate`, `string.trim`, and `string.replace` are tested and have no problems.)

**Comment by lamchakchan** [comment]
(Edited to add object `rename`)

**Comment by lamchakchan** [comment]
(Edited to add object `and` and `or`)

**Comment by lamchakchan** [comment]
@WesTyler seems like the `Object.type()` API is going to require some Joi PR's to add pass through for `Function:constructor` pointers.  As of right now, when you setup a schema with the following:

```Javascript
let CustomClass = function() {};
CustomClass.prototype = {};

Joi.object().keys({
    prop1 : Joi.any()
}).type(CustomClass);
```

We get from `Joi` in their `schema` the following:

```Javascript
{
   ...
   _tests : [{
      func : [Func], // not of type CustomClass
      name : 'type',
      arg : 'CustomClass'
   }]
}
```

There is a way for us to create a new constructor based off of the `arg` value.  But this then becomes a totally new Object entity that does not validate when using `instanceof` keyword against the original one that was defined.

**Comment by lamchakchan** [comment]
(Edited to add object `unknown`)

**Comment by lamchakchan** [comment]
(Edited to add object `schema`)

**Comment by WesTyler** [comment]
(Edited to indicate lack of coverage on new Joi v10 features: `boolean().truthy()`/`.falsy()` and `string().regex(/pattern/, { invert: true })`)

**Comment by lamchakchan** [comment]
(Edited to add object `type`)

**Comment by lamchakchan** [comment]
(Edited to add boolean `truthy` and `falsy`)

**Comment by WesTyler** [comment]
Closing this to mark where v1 is at the time of release.
