### ISSUE TITLE
Discussion of API.md

### ISSUE THREAD

**Issue by WesTyler** [xogroup/felicity#30]
Please leave any comments, questions, concerns, advice, etc regarding the API.md documentation. 

Feel free to make a PR to rewrite anything you want, but please tag the commit/PR with this issue so that I can see what was changed in one central spot. I like to learn and improve. :)

**Comment by devinivy** [comment]
It's unclear to me from the docs whether `instance.example()` populates `instance` with the example data or not.  Does it return another instance, the same instance, or a plain javascript object?

**Comment by WesTyler** [comment]
Ah, cool. You're correct, it returns a plain JS object.

I'll update to clarify. Thanks!

**Comment by WesTyler** [comment]
I'm going to go ahead and close this. If anyone notices issues with the documentation, just create a new issue :)
