### ISSUE TITLE
Object.rename should utilize Joi describe api

### ISSUE THREAD

**Issue by WesTyler** [xogroup/felicity#57]
Pending approval/implementation of https://github.com/hapijs/joi/issues/1026 , the Felicity `lib/helpers.js/internals.object` method should not rely on `_inner` properties anymore.

**Comment by WesTyler** [comment]
Oops. Totally just outed Felicity on the Joi issue by linking above... I added a pre-release disclaimer to our README in case anybody links over here from Joi... 😬

**Comment by lamchakchan** [comment]
Agreed!

**Comment by lamchakchan** [comment]
@WesTyler I put in a fix [here](https://github.com/hapijs/joi/pull/1027)

**Comment by WesTyler** [comment]
Awesome, just saw it and commented to link to the issue I filed :)

Thanks for knocking out so much today!
