### ISSUE TITLE
Create templates for issue and PR submissions

### ISSUE THREAD

**Issue by lamchakchan** [xogroup/felicity#69]
[templating example](https://github.com/blog/2111-issue-and-pull-request-templates)

**Comment by WesTyler** [comment]
Looks like the ISSUE_TEMPLATE worked. Going to go ahead and make a PR template. I still won't close this issue until you have a chance to weigh in on the templates themselves.

**Comment by WesTyler** [comment]
Hey @lamchakchan - I added the issue/PR templates and verified they are working as expected. I just wanted a second set of eyes on wording/details before closing this issue. Will you please PR and/or close this when you are satisfied?
