### ISSUE TITLE
Support inverted string.regex pattern

### ISSUE THREAD

**Issue by WesTyler** [xogroup/felicity#73]
With the release of Joi (v10)[https://github.com/hapijs/joi/issues/1037], there is a new string regex option to implement:

[`Joi.string().regex(/pattern/, { invert: true })`](https://github.com/hapijs/joi/blob/master/API.md#stringregexpattern-name--options)

**Comment by lamchakchan** [comment]
Does not look like `RandExp` processes negative look aheads.  What do you think of supplying our own statick regex pattern when `invert` is `true`?

**Comment by WesTyler** [comment]
Yeah I was just thinking this through. I think that is a good compromise for v1. I imagine we will get issues reported if people use inverted regexes and have a problem with that.

**Comment by WesTyler** [comment]
I don't have much of an opinion on what that static pattern should be. Right now I'm thinking something silly like `/[a-d]{3,6}/`. Thoughts?
