### ISSUE TITLE
Upgrade to Joi v10.0.x

### ISSUE THREAD

**Issue by WesTyler** [xogroup/felicity#74]
Joi v10.0.0 has been released. Let's jump on board.

**Comment by lamchakchan** [comment]
@WesTyler should I close or are you managing these for tracking?

**Comment by WesTyler** [comment]
I'm managing :) Once the other v10-related issues are closed I'll close this one. I'm taking a look at thing right now

**Comment by WesTyler** [comment]
DONE. Going to update the README to remove disclaimer and publish v1 as soon as I get the blessing on the blog post to accompany.
