### ISSUE TITLE
Allow dynamic constructor names

### ISSUE THREAD

**Issue by WesTyler** [xogroup/felicity#98]
#### What are you trying to achieve or the steps to reproduce ?
Constructor functions created by `Felicity.entityFor` currently have the constructor name `Constructor`. There should be an option available to `entityFor` to override this name.

#### What result did you expect ?
```js
> const User = Felicity.entityFor(Joi.object(), { config: { constructorName: 'User' } })
> new User()
User {}
```

#### What result did you observe ?
```js
> const User = Felicity.entityFor(Joi.object())
> new User()
Constructor {}
```

**Comment by devinivy** [comment]
I don't think this is necessary,
```js
> const User = class User extends Felicity.entityFor(Joi.object()) {};
> new User();
User {}
```

**Comment by WesTyler** [comment]
Nah,  definitely not necessary. But useful in debugging. I spent 30 minutes
trying to track down why something was passing around a `Constructor {}`
instance before remembering that's what I named the `entityFor` returned
function 😵😂

**Comment by devinivy** [comment]
What I mean is, is there a reason not to use `class X extends Felicity.entityFor(schema) {}` to set the constructor's name in a more natural way?  (Even if it's just for debugging.)

**Comment by WesTyler** [comment]
Oh geez.... that's what I get for reading your response on my phone and replying via email instead of actually visiting the issue and paying close attention to the code snippet you included...

Good call. I like that better than including it in the Felicity source. I'm turning this into a "documentation" ticket to show that example instead :D

Thanks!
